name: sap
favicon: null
layout_spectrum: 0.6340824868530035
typography_spectrum: 0.5336774804163724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.35538657545112073
  lightness: 0.597694712691009
  saturation: 0.390194232808426
  rhythmicContrast: 0.1548214196227491
purpose: []
